#!/bin/bash
# Created by 


echo "Script by vps-murah.net"
echo "Terimakasih sudah berlangganan di vps-murah.net"
echo "===============================================";
echo " ";
if [ -e "/root/log-limit.txt" ]; then
echo "User yang dikick oleh user-limit adalah";
echo "Waktu - Username - Jumlah Multilogin"
echo "-------------------------------------";
cat /root/log-limit.txt
else
echo " Tidak ada user yang melakukan pelanggaran"
echo " Atau"
echo " Script user-limit belum dijalankan"
fi
echo " ";
echo "===============================================";
echo "Script Created by http://seller.vps";
echo "Terimakasih sudah berlanggan di seller.vps";
