#!/bin/bash
# Created by 
# Uban User.

read -p "Masukkan Username yang ingin anda unban: " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti passwordnya
passwd -u $username
clear
  echo "Script by seller-vps.net"
  echo "Terimakasih sudah berlangganan di seller-vps.net"
  echo " "
  echo "-----------------------------------------------"
  echo -e "Username ${blue}$username${NC} Sudah berhasil di ${green}UNBAN${NC}."
  echo -e "Password untuk Username ${blue}$username${NC} sudah dikembalikan"
  echo "seperti semula"
  echo "-----------------------------------------------"
else
echo "Username tidak ditemukan di server anda"
    exit 1
fi